export const games = [
  { id: 1, name: "7 Days to Die", slug: "7-days-to-die", logo: "/games/7d2d.png" },
  { id: 2, name: "ARK: Survival Evolved", slug: "ark-survival-evolved", logo: "/games/ark.png" },
  { id: 3, name: "ARK: Survival Ascended", slug: "ark-survival-ascended", logo: "/games/arksa.png" },
  { id: 4, name: "Rust", slug: "rust", logo: "/games/rust.png" },
  { id: 5, name: "Valheim", slug: "valheim", logo: "/games/valheim.png" },
  { id: 6, name: "Conan Exiles", slug: "conan-exiles", logo: "/games/conan.png" },
  { id: 7, name: "DayZ", slug: "dayz", logo: "/games/dayz.png" },
  { id: 8, name: "The Forest", slug: "the-forest", logo: "/games/theforest.png" },
  { id: 9, name: "Sons of the Forest", slug: "sons-of-the-forest", logo: "/games/sonsoftheforest.png" },
  { id: 10, name: "Subnautica", slug: "subnautica", logo: "/games/subnautica.png" },
  { id: 11, name: "Subnautica: Below Zero", slug: "subnautica-below-zero", logo: "/games/belowzero.png" },
  { id: 12, name: "Green Hell", slug: "green-hell", logo: "/games/greenhell.png" },
  { id: 13, name: "The Long Dark", slug: "the-long-dark", logo: "/games/thelongdark.png" },
  { id: 14, name: "Astroneer", slug: "astroneer", logo: "/games/astroneer.png" },
  { id: 15, name: "Raft", slug: "raft", logo: "/games/raft.png" },
  { id: 16, name: "Scum", slug: "scum", logo: "/games/scum.png" },
  { id: 17, name: "V Rising", slug: "v-rising", logo: "/games/vrising.png" },
  { id: 18, name: "Icarus", slug: "icarus", logo: "/games/icarus.png" },
  { id: 19, name: "Project Zomboid", slug: "project-zomboid", logo: "/games/zomboid.png" },
  { id: 20, name: "Empyrion: Galactic Survival", slug: "empyrion", logo: "/games/empyrion.png" },
  { id: 21, name: "State of Decay 2", slug: "state-of-decay-2", logo: "/games/sod2.png" },
  { id: 22, name: "Enshrouded", slug: "enshrouded", logo: "/games/enshrouded.png" },
  { id: 23, name: "Grounded", slug: "grounded", logo: "/games/grounded.png" },
  { id: 24, name: "Grounded 2", slug: "grounded-2", logo: "/games/grounded2.png" },
  { id: 25, name: "No Man's Sky", slug: "no-mans-sky", logo: "/games/nomanssky.png" },
  { id: 26, name: "The Isle", slug: "the-isle", logo: "/games/theisle.png" },
  { id: 27, name: "Palworld", slug: "palworld", logo: "/games/palworld.png" },
];